name: Default MkDocs Pages

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.12"
      mkdocs-args:
        required: false
        type: string
        default: "--strict"
      working-directory:
        required: false
        type: string
        default: "."

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      
      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: poetry install --with dev,docs

      - name: Build MkDocs
        working-directory: ${{ inputs.working-directory }}
        run: poetry run mkdocs build ${{ inputs.mkdocs-args }}
      
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --root-dir ${{ inputs.working-directory }}/site '${{ inputs.working-directory }}/site/**/*.html'
          fail: true

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '${{ inputs.working-directory }}/site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
